services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./data/pg:/var/lib/postgresql/data:Z"
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s

  pgadmin:
    depends_on:
      db:
        condition: service_healthy
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    user: root
    volumes:
      - "./data/pgadmin:/var/lib/pgadmin:Z"
    ports:
      - "8420:80"

  langflow:
    image: langflowai/langflow:v1.1.1
    depends_on:
      db:
        condition: service_healthy
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@db:5432/langflow
    volumes:
      - "./data/langflow:/app/langflow:Z"
    ports:
      - "7860:7860"
